<a href="https://colab.research.google.com/github/fcernafukuzaki/GoogleColab/blob/master/Clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

import pandas as pd

# Trabajando con tensores

---



In [4]:
torch.__version__

'1.4.0'

In [5]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [8]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[1.5804e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])


tensor([[0.9025, 0.6991],
        [0.3963, 0.6318]])

In [9]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.0707, 0.6581],
        [0.9475, 0.8290]])

In [15]:
result = tensor_b + tensor_c
print(result)
result.shape
reshaped = result.view(1, 4)
print(reshaped)

tensor([[0.9732, 1.3571],
        [1.3438, 1.4608]])
tensor([[0.9732, 1.3571, 1.3438, 1.4608]])


In [16]:
reshaped = result.view(4, 1)
reshaped

tensor([[0.9732],
        [1.3571],
        [1.3438],
        [1.4608]])

In [17]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(points)
points[0][1]

tensor([[1., 2.],
        [3., 4.]])


tensor(2.)

In [20]:
points[0][1] = 2.5
points


tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])

In [22]:
points.storage()

 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [23]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [25]:
p_t = points.t()
print(p_t)
print(p_t.stride())

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])
(1, 2)


In [26]:
tensor_x = torch.tensor([1, 2, 3, 4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [30]:
numpyArray = np.random.randn(2, 2)
from_numpy = torch.from_numpy(numpyArray)
print(from_numpy)

tensor([[ 0.1473, -0.4127],
        [-0.9522,  0.7378]], dtype=torch.float64)


# Representar datos con tensores

---



In [31]:
# Media
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor(-0.1199, dtype=torch.float64)
tensor([-0.4024,  0.1626], dtype=torch.float64)
tensor([-0.1327, -0.1072], dtype=torch.float64)


In [32]:
# Desviación estándar
torch.std(from_numpy, dim=1)

tensor([0.3960, 1.1950], dtype=torch.float64)

In [0]:
torch.save(from_numpy, 'tensor.t')

In [0]:
load = torch.load('tensor.t')

In [36]:
load

tensor([[ 0.1473, -0.4127],
        [-0.9522,  0.7378]], dtype=torch.float64)

In [43]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [44]:
# visualizar columnas del dataset
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [51]:
# No considerar las filas que no tengan valor.
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0, how='any')
# Subset de las columnas seleccionadas.
columns = subset.columns[1:]
# Pasar la información de los jugadores a un tensor.
# Se fuerza a que los valores sean flotantes para realizar los cálculos con las operaciones.
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [52]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [53]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [54]:
# Media
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [55]:
# Desviación Estándar
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [56]:
# Normalizar los datos.
norm = (data - mean) / torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [61]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

goodMean, averageMean, notSoGoodMean


(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([24.3676,  1.0106,  2.8864,  2.2208]))

In [62]:
# Itera el índice y todos los valores (args)
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
