<a href="https://colab.research.google.com/github/fcernafukuzaki/GoogleColab/blob/master/Clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

# Trabajando con tensores

---



In [4]:
torch.__version__

'1.4.0'

In [5]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [8]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[1.5804e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])


tensor([[0.9025, 0.6991],
        [0.3963, 0.6318]])

In [9]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.0707, 0.6581],
        [0.9475, 0.8290]])

In [15]:
result = tensor_b + tensor_c
print(result)
result.shape
reshaped = result.view(1, 4)
print(reshaped)

tensor([[0.9732, 1.3571],
        [1.3438, 1.4608]])
tensor([[0.9732, 1.3571, 1.3438, 1.4608]])


In [16]:
reshaped = result.view(4, 1)
reshaped

tensor([[0.9732],
        [1.3571],
        [1.3438],
        [1.4608]])

In [17]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(points)
points[0][1]

tensor([[1., 2.],
        [3., 4.]])


tensor(2.)

In [20]:
points[0][1] = 2.5
points


tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])

In [22]:
points.storage()

 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [23]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [25]:
p_t = points.t()
print(p_t)
print(p_t.stride())

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])
(1, 2)


In [26]:
tensor_x = torch.tensor([1, 2, 3, 4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [29]:
numpyArray = np.random.randn(2, 2)
torch.from_numpy(numpyArray)

tensor([[ 1.3116,  1.0023],
        [-0.7811,  0.8175]], dtype=torch.float64)